version: "3.9"

services:
  # MySQL service
  db:
    image: mysql:8.0
    container_name: aem-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: admin143
      MYSQL_PASSWORD: admin123
      MYSQL_USER: user
    volumes:
      - mysql-data:/var/lib/mysql


  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  # Web application service
  my-webapi:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8081:5218"
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin123
    depends_on:
      - db

  toolbox:
    image: ubuntu
    command: ["sleep", "inf"]

volumes:
  # Volume to store MySQL data
  mysql-data:
