// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApi.Models;

#nullable disable

namespace MyWebApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyWebApi.Models.PlatformWellActualResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("UniqueName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PlatformWellActualResponse");
                });

            modelBuilder.Entity("MyWebApi.Models.PlatformWellActualWell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int?>("PlatformWellActualResponseId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlatformWellActualResponseId");

                    b.ToTable("PlatformWellActualWell");
                });

            modelBuilder.Entity("MyWebApi.Models.PlatformWellDummyResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("UniqueName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlatformWellDummyResponse");
                });

            modelBuilder.Entity("MyWebApi.Models.PlatformWellDummyWell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int?>("PlatformWellDummyResponseId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PlatformWellDummyResponseId");

                    b.ToTable("PlatformWellDummyWell");
                });

            modelBuilder.Entity("MyWebApi.Models.PlatformWellActualWell", b =>
                {
                    b.HasOne("MyWebApi.Models.PlatformWellActualResponse", null)
                        .WithMany("Well")
                        .HasForeignKey("PlatformWellActualResponseId");
                });

            modelBuilder.Entity("MyWebApi.Models.PlatformWellDummyWell", b =>
                {
                    b.HasOne("MyWebApi.Models.PlatformWellDummyResponse", null)
                        .WithMany("Well")
                        .HasForeignKey("PlatformWellDummyResponseId");
                });

            modelBuilder.Entity("MyWebApi.Models.PlatformWellActualResponse", b =>
                {
                    b.Navigation("Well");
                });

            modelBuilder.Entity("MyWebApi.Models.PlatformWellDummyResponse", b =>
                {
                    b.Navigation("Well");
                });
#pragma warning restore 612, 618
        }
    }
}
